//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 北京赛车
{
    using System;
    using System.Collections.Generic;
    
    public partial class ssc1
    {
        public int id { get; set; }
        public string numbers { get; set; }
        public Nullable<int> lxwz { get; set; }
        public string period { get; set; }
    }
}
